name: DependencyTrack Upload

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  upload-sbom:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: run sbomb
        run: npm run dt
      
      - name: Upload SBOM to DependencyTrack
        run: |
          curl -X POST \
            -H "X-Api-Key: ${{ secrets.DT_SECRET_KEY }}" \
            -H "Content-Type: application/json" \
            -d @sbom.json \
            ${{ secrets.DT_SECRET_KEY }}/api/v1/bom
          echo "SBOM generated: sbom.json"

